Repository ttakkeun/Front_iOS, pull requests merged in 2024-08, with the labels that each got.

#69 Feat/home view
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/APITarget/ProductRecommendAPITarget.swift
  ttakkeun/ttakkeun/Components/Home/HomeAIRecommendProduct.swift
  ttakkeun/ttakkeun/SettingGroup/Fonts/Font.swift
  ttakkeun/ttakkeun/SettingGroup/Fonts/HSSanTokki.ttf
  ttakkeun/ttakkeun/SettingGroup/Fonts/SUIT-Bold.otf
  ttakkeun/ttakkeun/SettingGroup/Fonts/SUIT-ExtraBold.otf
  ttakkeun/ttakkeun/SettingGroup/Fonts/SUIT-ExtraLight.otf
  ttakkeun/ttakkeun/SettingGroup/Fonts/SUIT-Heavy.otf
  ttakkeun/ttakkeun/SettingGroup/Fonts/SUIT-Light.otf
  ttakkeun/ttakkeun/SettingGroup/Fonts/SUIT-Medium.otf
  ttakkeun/ttakkeun/SettingGroup/Fonts/SUIT-Regular.otf
  ttakkeun/ttakkeun/SettingGroup/Fonts/SUIT-SemiBold.otf
  ttakkeun/ttakkeun/SettingGroup/Fonts/SUIT-Thin.otf
  ttakkeun/ttakkeun/ViewGroup/HomeTab/CompactTodo.swift
  ttakkeun/ttakkeun/ViewGroup/HomeTab/HomeDragView.swift
  ttakkeun/ttakkeun/ViewGroup/HomeTab/HomeView.swift
  ttakkeun/ttakkeun/ViewModelGroup/ProductViewModel.swift
  ttakkeun/ttakkeun/ViewModelGroup/ScheduleViewModel.swift
Labels: :hammer: Refactor, :sparkles: Feature, :lipstick: UI

#73 🐛 메인 버튼 수정
  ttakkeun/ttakkeun/Components/ETC/MainButton.swift
Labels: :bug: BugFix

#71 Feat/qnafaqview완성
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/QnA/TopTenQuestion.swift
  ttakkeun/ttakkeun/DataModelGroup/QnaFaqData.swift
  ttakkeun/ttakkeun/DataModelGroup/QnaJson/CategoryQnaJsonData.json
  ttakkeun/ttakkeun/DataModelGroup/QnaJson/TopTenQnaJsonData.json
  ttakkeun/ttakkeun/EnumFile/PartItem.swift
  ttakkeun/ttakkeun/SettingGroup/Color.swift
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/QnA/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/QnA/QnAEar.colorset/Contents.json
  ttakkeun/ttakkeun/ViewGroup/QnaTab/QnaFAQView.swift
  ttakkeun/ttakkeun/ViewGroup/QnaTab/QnaHeaderView.swift
  ttakkeun/ttakkeun/ViewGroup/QnaTab/QnaTipsView.swift
  ttakkeun/ttakkeun/ViewModelGroup/QnaViewModel.swift
Labels: :sparkles: Feature, :lipstick: UI

#75 Feat/make profile
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/ETC/CustomTextField.swift
  ttakkeun/ttakkeun/Components/Profile/BirthSelect.swift
  ttakkeun/ttakkeun/Components/Profile/MakeProfileButtonCustom.swift
  ttakkeun/ttakkeun/Components/Profile/MakeProfileNameTag.swift
  ttakkeun/ttakkeun/Components/Profile/VarietySearch.swift
  ttakkeun/ttakkeun/DataModelGroup/PetProfile/CreatePetProfileRequestData.swift
  ttakkeun/ttakkeun/DataModelGroup/PetProfile/PetVarietyData.swift
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/프로필 생성/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/프로필 생성/check.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/프로필 생성/check.imageset/Frame 7405.pdf
  ttakkeun/ttakkeun/SettingGroup/Icon.swift
  ttakkeun/ttakkeun/ViewGroup/CreateProfileView.swift
  ttakkeun/ttakkeun/ViewModelGroup/CreateProfileViewModel.swift
Labels: :hammer: Refactor, :sparkles: Feature, :lipstick: UI

#76 Feat/make profile
  ttakkeun/ttakkeun/DataModelGroup/PetProfile/PetVarietyData.swift
Labels: :hammer: Refactor

#78 💄 온보딩 화면 구현(lottie 애니메이션 활용)
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ttakkeun/ttakkeun/SettingGroup/Color.swift
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/Login/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/Login/Onboarding.colorset/Contents.json
  ttakkeun/ttakkeun/ViewGroup/LoginView/LoginView.swift
  ttakkeun/ttakkeun/ViewGroup/LoginView/Onboarding.json
  ttakkeun/ttakkeun/ViewGroup/LoginView/OnboardingView.swift
Labels: :lipstick: UI

#80 Refactor/navigation
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ttakkeun/ttakkeun/APITarget/JournalAPITarget.swift
  ttakkeun/ttakkeun/Components/ETC/CustomNavigation.swift
  ttakkeun/ttakkeun/Components/Journal/AnswerButton.swift
  ttakkeun/ttakkeun/Components/Journal/DiagnosticImages.swift
  ttakkeun/ttakkeun/Components/Journal/SelctCareButton.swift
  ttakkeun/ttakkeun/DataModelGroup/Journal/JournalQuestionsData.swift
  ttakkeun/ttakkeun/DataModelGroup/Journal/RegistJournalData.swift
  ttakkeun/ttakkeun/EnumFile/AnswerValue.swift
  ttakkeun/ttakkeun/EnumFile/PartItem.swift
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/answerCheck.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/answerCheck.imageset/answerCheck.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/answerNotCheck.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/answerNotCheck.imageset/answerNotCheck.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/buttonClaw.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/buttonClaw.imageset/buttonClaw.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/buttonEar.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/buttonEar.imageset/buttonEar.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/buttonEye.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/buttonEye.imageset/buttonEye.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/buttonHair.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/buttonHair.imageset/buttonHair.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/buttonTeeth.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/buttonTeeth.imageset/buttonTeeth.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/imageRemove.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/imageRemove.imageset/imageRemove.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/petCamera.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/petCamera.imageset/petCamera.pdf
  ttakkeun/ttakkeun/SettingGroup/Icon.swift
  ttakkeun/ttakkeun/ViewGroup/Diagnosis/RegistDiagnosisFlowView.swift
  ttakkeun/ttakkeun/ViewGroup/Diagnosis/RegistDiagnosisPageContents.swift
  ttakkeun/ttakkeun/ViewModelGroup/RegistJournalViewModel.swift
Labels: :hammer: Refactor, :lipstick: UI

#81 ♻️ 네비게이션 초기화 변경
  ttakkeun/ttakkeun/Components/ETC/CustomNavigation.swift
Labels: :hammer: Refactor

#82 Feat/diagnosis header
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/APITarget/JournalAPITarget.swift
  ttakkeun/ttakkeun/DataModelGroup/Journal/JournalListData.swift
  ttakkeun/ttakkeun/EnumFile/DiagnosisSegment.swift
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/DiagnosisBackground.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/DiagnosisBackground.imageset/DiagnosisBackground.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/bubble.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/bubble.imageset/bubble.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/bubbleLogo.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/bubbleLogo.imageset/bubbleLogo.pdf
  ttakkeun/ttakkeun/SettingGroup/Color.swift
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/Diagnosis/LineColor.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Fonts/Font.swift
  ttakkeun/ttakkeun/SettingGroup/Icon.swift
  ttakkeun/ttakkeun/ViewGroup/Diagnosis/DiagnosisHeader.swift
  ttakkeun/ttakkeun/ViewGroup/Diagnosis/DiagnosisView.swift
  ttakkeun/ttakkeun/ViewGroup/Diagnosis/JournalList.swift
  ttakkeun/ttakkeun/ViewModelGroup/DiagnosisViewModel.swift
Labels: :hammer: Refactor, :lipstick: UI

#84 Feat/api connect
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/APITarget/APIBaseURL.swift
  ttakkeun/ttakkeun/APITarget/JournalAPITarget.swift
  ttakkeun/ttakkeun/APITarget/PetProfileAPITarget.swift
  ttakkeun/ttakkeun/APITarget/ProductRecommendAPITarget.swift
  ttakkeun/ttakkeun/APITarget/ScheduleAPITarget.swift
  ttakkeun/ttakkeun/APITarget/TodoAPITarget.swift
  ttakkeun/ttakkeun/APITarget/UserLoginAPITarget.swift
  ttakkeun/ttakkeun/Components/Diagnosis/AnswerButton.swift
  ttakkeun/ttakkeun/Components/Diagnosis/DiagnosisHeader.swift
  ttakkeun/ttakkeun/Components/Diagnosis/DiagnosticImages.swift
  ttakkeun/ttakkeun/Components/Diagnosis/JournalList.swift
  ttakkeun/ttakkeun/Components/Diagnosis/SelctCareButton.swift
  ttakkeun/ttakkeun/DataModelGroup/ToDo/CorrectionTodo.swift
  ttakkeun/ttakkeun/DataModelGroup/ToDo/CreateTodoData.swift
  ttakkeun/ttakkeun/ViewGroup/Diagnosis/RegistDiagnosisPageContents.swift
Labels: :globe_with_meridians: API, :hammer: Refactor

#90 Feat/journal list
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/APITarget/JournalAPITarget.swift
  ttakkeun/ttakkeun/Components/Diagnosis/DiagnosisTopbutton.swift
  ttakkeun/ttakkeun/Components/Diagnosis/JournalListCard.swift
  ttakkeun/ttakkeun/Components/Diagnosis/NotJournalList.swift
  ttakkeun/ttakkeun/Components/ETC/TopStatusBar.swift
  ttakkeun/ttakkeun/DataModelGroup/Journal/JournalListData.swift
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/loadingBg.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/loadingBg.imageset/loadingBg.pdf
  ttakkeun/ttakkeun/SettingGroup/Icon.swift
  ttakkeun/ttakkeun/ViewGroup/Diagnosis/DiagnosingView.swift
  ttakkeun/ttakkeun/ViewGroup/Diagnosis/DiagnosisHeader.swift
  ttakkeun/ttakkeun/ViewGroup/Diagnosis/DiagnosisView.swift
  ttakkeun/ttakkeun/ViewGroup/Diagnosis/JournalListView.swift
  ttakkeun/ttakkeun/ViewModelGroup/DiagnosisViewModel.swift
  ttakkeun/ttakkeun/ViewModelGroup/Diagnostic/DiagnosticResultViewModel.swift
  ttakkeun/ttakkeun/ViewModelGroup/Diagnostic/JournalListViewModel.swift
Labels: :globe_with_meridians: API, :hammer: Refactor, :lipstick: UI

#92 Feat/my page
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/마이페이지/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/마이페이지/heartTips.imageset/3dicons.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/마이페이지/heartTips.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/마이페이지/pencil.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/마이페이지/pencil.imageset/Group 7114.pdf
  ttakkeun/ttakkeun/SettingGroup/Color.swift
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/MyPage/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/MyPage/exit.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Fonts/Font.swift
  ttakkeun/ttakkeun/SettingGroup/Icon.swift
  ttakkeun/ttakkeun/ViewGroup/MyPage/MyPageDetailView.swift
  ttakkeun/ttakkeun/ViewGroup/MyPage/MyPageView.swift
  ttakkeun/ttakkeun/ViewModelGroup/MyPageViewModel.swift
Labels: :globe_with_meridians: API, :hammer: Refactor

#94 Feat/agree option
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/Login/AgreementDetailSheet.swift
  ttakkeun/ttakkeun/DataModelGroup/Login/AgreementData.swift
  ttakkeun/ttakkeun/DataModelGroup/Login/AgreementDetailData.swift
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/로그인 화면/uncheck.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/로그인 화면/uncheck.imageset/Group 7136.pdf
  ttakkeun/ttakkeun/SettingGroup/Icon.swift
  ttakkeun/ttakkeun/ViewGroup/LoginView/AgreementView.swift
  ttakkeun/ttakkeun/ViewModelGroup/AgreementViewModel.swift
Labels: :hammer: Refactor, :lipstick: UI

#98 Feat/create journal
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/Diagnosis/AnswerButton.swift
  ttakkeun/ttakkeun/Components/Diagnosis/DiagnosticImages.swift
  ttakkeun/ttakkeun/Components/Diagnosis/SelectCareButton.swift
  ttakkeun/ttakkeun/DataModelGroup/Journal/JournalQuestionsData.swift
  ttakkeun/ttakkeun/DataModelGroup/Journal/RegistJournalData.swift
  ttakkeun/ttakkeun/EnumFile/AnswerValue.swift
  ttakkeun/ttakkeun/ViewGroup/Diagnosis/JournalQuestionView.swift
  ttakkeun/ttakkeun/ViewGroup/Diagnosis/RegistDiagnosisFlowView.swift
  ttakkeun/ttakkeun/ViewGroup/Diagnosis/RegistDiagnosisPageContents.swift
  ttakkeun/ttakkeun/ViewModelGroup/RegistJournalViewModel.swift
Labels: :globe_with_meridians: API, :sparkles: Feature, :lipstick: UI

#99 ✨ TextEditor 모디피어 생성
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/ETC/CustomTextEditor.swift
Labels: :sparkles: Feature, :lipstick: UI

#104 Feat/create journal
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/APITarget/JournalAPITarget.swift
  ttakkeun/ttakkeun/Components/Diagnosis/CheckQnAComponent.swift
  ttakkeun/ttakkeun/Components/Diagnosis/DiagnosticImages.swift
  ttakkeun/ttakkeun/Components/Diagnosis/JournalListCard.swift
  ttakkeun/ttakkeun/Components/ETC/CustomNavigation.swift
  ttakkeun/ttakkeun/Components/ETC/CustomTextEditor.swift
  ttakkeun/ttakkeun/DataModelGroup/Journal/CheckJournalQnA.swift
  ttakkeun/ttakkeun/DataModelGroup/Journal/JournalQuestionsData.swift
  ttakkeun/ttakkeun/DataModelGroup/Journal/RegistJournalData.swift
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/close.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/close.imageset/Group 7111.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/leftCat.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/leftCat.imageset/leftCat.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/rightDog.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/rightDog.imageset/rightDog.pdf
  ttakkeun/ttakkeun/SettingGroup/Icon.swift
  ttakkeun/ttakkeun/SettingGroup/ttakkeunApp.swift
  ttakkeun/ttakkeun/ViewGroup/Diagnosis/CheckQnAView.swift
  ttakkeun/ttakkeun/ViewGroup/Diagnosis/JournalQuestionView.swift
  ttakkeun/ttakkeun/ViewGroup/Diagnosis/RegistDiagnosisFlowView.swift
  ttakkeun/ttakkeun/ViewGroup/Diagnosis/RegistDiagnosisPageContents.swift
  ttakkeun/ttakkeun/ViewModelGroup/RegistJournalViewModel.swift
Labels: :globe_with_meridians: API, :hammer: Refactor, :sparkles: Feature

#105 TipsView랑 Tip공유View
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ttakkeun/ttakkeun/APITarget/QnaTipsAPITarget.swift
  ttakkeun/ttakkeun/Components/ETC/FloatingButton.swift
  ttakkeun/ttakkeun/Components/QnA/FloatingWrtieBtn.swift
  ttakkeun/ttakkeun/Components/QnA/TipContent.swift
  ttakkeun/ttakkeun/Components/QnA/WriteCategory.swift
  ttakkeun/ttakkeun/DataModelGroup/QnA/QnaHeartChangeData.swift
  ttakkeun/ttakkeun/DataModelGroup/QnA/QnaPostTipsData.swift
  ttakkeun/ttakkeun/DataModelGroup/QnA/QnaTipsData.swift
  ttakkeun/ttakkeun/EnumFile/TipsCategorySegment.swift
  ttakkeun/ttakkeun/File/ImagePicker/QnaImagePicker.swift
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/camera.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/camera.imageset/Photo camera.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/cancel.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/cancel.imageset/Group 7137.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/write.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/write.imageset/Group 7114.pdf
  ttakkeun/ttakkeun/SettingGroup/Icon.swift
  ttakkeun/ttakkeun/ViewGroup/Qna/QnaHeaderView.swift
  ttakkeun/ttakkeun/ViewGroup/Qna/QnaTipsView.swift
  ttakkeun/ttakkeun/ViewGroup/Qna/QnaView.swift
  ttakkeun/ttakkeun/ViewGroup/Qna/QnaWriteTipsView.swift
  ttakkeun/ttakkeun/ViewGroup/TabView/TabView.swift
  ttakkeun/ttakkeun/ViewModelGroup/QnaTipsViewModel.swift
  ttakkeun/ttakkeun/ViewModelGroup/QnaWriteTipsViewModel.swift
Labels: :globe_with_meridians: API, :sparkles: Feature, :lipstick: UI

#106 FAQ에 Json파일이랑, 레이아웃 수정
  ttakkeun/ttakkeun/Components/QnA/TopTenQuestion.swift
  ttakkeun/ttakkeun/DataModelGroup/QnA/CategoryQnaJsonData.json
  ttakkeun/ttakkeun/DataModelGroup/QnA/TopTenQnaJsonData.json
  ttakkeun/ttakkeun/ViewGroup/Qna/QnaFAQView.swift
Labels: :hammer: Refactor, :lipstick: UI

#107 ✨ 진단 생성 후, 결과 보는 뷰 작성
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/APITarget/DiagnosticResultAPITarget.swift
  ttakkeun/ttakkeun/Components/Diagnosis/DiagnosisProductView.swift
  ttakkeun/ttakkeun/DataModelGroup/Diagnostic/DiagnosisData.swift
  ttakkeun/ttakkeun/DataModelGroup/ResponseData.swift
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일지/diagnosisBackground.imageset/diagnosisBackground.pdf
  ttakkeun/ttakkeun/ViewGroup/Diagnosis/DiagnosisResultView.swift
  ttakkeun/ttakkeun/ViewModelGroup/Diagnostic/DiagnosticResultViewModel.swift
  ttakkeun/ttakkeun/ViewModelGroup/Profile/CreateProfileViewModel.swift
  ttakkeun/ttakkeun/ViewModelGroup/Profile/ProfileCardViewModel.swift
  ttakkeun/ttakkeun/ViewModelGroup/QnA/QnaTipsViewModel.swift
  ttakkeun/ttakkeun/ViewModelGroup/QnA/QnaViewModel.swift
  ttakkeun/ttakkeun/ViewModelGroup/QnA/QnaWriteTipsViewModel.swift
Labels: :globe_with_meridians: API, :sparkles: Feature

#109 Feat/api
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/APITarget/APIBaseURL.swift
  ttakkeun/ttakkeun/APITarget/UserLoginAPITarget.swift
  ttakkeun/ttakkeun/Components/ETC/CustomNavigation.swift
  ttakkeun/ttakkeun/DataModelGroup/Login/LoginResponseData.swift
  ttakkeun/ttakkeun/DataModelGroup/Login/SignUpData.swift
  ttakkeun/ttakkeun/DataModelGroup/Login/SignUpResponseData.swift
  ttakkeun/ttakkeun/DataModelGroup/ResponseData.swift
  ttakkeun/ttakkeun/EnumFile/AppState.swift
  ttakkeun/ttakkeun/File/KeyChain/UserInfo.swift
  ttakkeun/ttakkeun/File/LoginManager/AppleLoginManager.swift
  ttakkeun/ttakkeun/File/Navigation/NavigationDestination.swift
  ttakkeun/ttakkeun/File/Navigation/NavigationRoutingView.swift
  ttakkeun/ttakkeun/File/TokenRefresh/AuthAPITarget.swift
  ttakkeun/ttakkeun/File/TokenRefresh/TokenProvider.swift
  ttakkeun/ttakkeun/File/TokenRefresh/TokenResponse.swift
  ttakkeun/ttakkeun/SettingGroup/ttakkeunApp.swift
  ttakkeun/ttakkeun/ViewGroup/Diagnosis/DiagnosisResultView.swift
  ttakkeun/ttakkeun/ViewGroup/LoginView/LoginView.swift
  ttakkeun/ttakkeun/ViewGroup/LoginView/OnboardingView.swift
  ttakkeun/ttakkeun/ViewGroup/LoginView/SignupView.swift
  ttakkeun/ttakkeun/ViewModelGroup/AgreementViewModel.swift
  ttakkeun/ttakkeun/ViewModelGroup/LoginOnBoarding/AppFlowViewModel.swift
  ttakkeun/ttakkeun/ViewModelGroup/LoginOnBoarding/LoginViewModel.swift
  ttakkeun/ttakkeun/ViewModelGroup/Profile/ProfileCardViewModel.swift
Labels: :globe_with_meridians: API, :sparkles: Feature, :lipstick: UI

#111 Feat/diary to do card
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/Diary/TodoCard.swift
  ttakkeun/ttakkeun/Components/Home/ToDoCheckList.swift
  ttakkeun/ttakkeun/File/Protocol/TodoCheckProtocol.swift
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/basePlus.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/basePlus.imageset/basePlus.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/minus.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/minus.imageset/Frame 7642.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/plus.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/plus.imageset/plus.pdf
  ttakkeun/ttakkeun/SettingGroup/Icon.swift
  ttakkeun/ttakkeun/ViewModelGroup/Diary/CustomDiaryViewModel.swift
  ttakkeun/ttakkeun/ViewModelGroup/Diary/TodoCheckViewModel.swift
  ttakkeun/ttakkeun/ViewModelGroup/LoginOnBoarding/AgreementViewModel.swift
  ttakkeun/ttakkeun/ViewModelGroup/ScheduleViewModel.swift
Labels: :hammer: Refactor, :lipstick: UI

#112 Recommend탭 컴포넌트 끝냄
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/Recommend/ProductSheetView.swift
  ttakkeun/ttakkeun/Components/Recommend/RecommendProduct.swift
  ttakkeun/ttakkeun/Components/Recommend/RecommendProductbyAI.swift
  ttakkeun/ttakkeun/Components/Recommend/RecommendSegment.swift
  ttakkeun/ttakkeun/DataModelGroup/RecommendProductData.swift
  ttakkeun/ttakkeun/EnumFile/RecommendProductSegment.swift
Labels: :lipstick: UI

#114 Feat/make profile
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/Profile/BirthSelect.swift
Labels: :hammer: Refactor

#116 ✨ 프로필 뷰 API 비동기 처리
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/APITarget/PetProfileAPITarget.swift
  ttakkeun/ttakkeun/Components/Profile/ProfileSelect.swift
  ttakkeun/ttakkeun/DataModelGroup/PetProfile/CreatePetProfileRequestData.swift
  ttakkeun/ttakkeun/DataModelGroup/PetProfile/PetProfileData.swift
  ttakkeun/ttakkeun/DataModelGroup/PetProfile/PetProfileImageData.swift
  ttakkeun/ttakkeun/File/Navigation/NavigationRoutingView.swift
  ttakkeun/ttakkeun/File/PetState.swift
  ttakkeun/ttakkeun/File/TokenRefresh/TokenProvider.swift
  ttakkeun/ttakkeun/ViewGroup/CreateProfileView.swift
  ttakkeun/ttakkeun/ViewGroup/ProfileView.swift
  ttakkeun/ttakkeun/ViewModelGroup/Profile/CreateProfileViewModel.swift
  ttakkeun/ttakkeun/ViewModelGroup/Profile/ProfileCardViewModel.swift
Labels: :globe_with_meridians: API, :hammer: Refactor, :sparkles: Feature

#118 ♻️ 프로필 뷰 appState 탭뷰 전환되도록 수정
  ttakkeun/ttakkeun/Components/Profile/ProfileSelect.swift
  ttakkeun/ttakkeun/EnumFile/AppState.swift
  ttakkeun/ttakkeun/File/PetState.swift
  ttakkeun/ttakkeun/SettingGroup/ttakkeunApp.swift
  ttakkeun/ttakkeun/ViewGroup/ProfileView.swift
  ttakkeun/ttakkeun/ViewGroup/TabView/TabView.swift
  ttakkeun/ttakkeun/ViewModelGroup/LoginOnBoarding/AppFlowViewModel.swift
Labels: :globe_with_meridians: API, :hammer: Refactor

#119 ♻️ 날짜 선택 시, 초기에 아무것도 선택되지 않게 수정
  ttakkeun/ttakkeun/Components/Profile/BirthSelect.swift
Labels: :hammer: Refactor

#120 ♻️ 앱 아이콘 등록
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/AppIcon.appiconset/1024.png
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/AppIcon.appiconset/114.png
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/AppIcon.appiconset/120 1.png
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/AppIcon.appiconset/120.png
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/AppIcon.appiconset/180.png
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/AppIcon.appiconset/40.png
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/AppIcon.appiconset/58.png
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/AppIcon.appiconset/60.png
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/AppIcon.appiconset/80.png
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/AppIcon.appiconset/87.png
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: :lipstick: UI

#121 Api/hom view
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/Home/HomeAINotRecommend.swift
  ttakkeun/ttakkeun/Components/Home/HomeBackCard.swift
  ttakkeun/ttakkeun/Components/Home/HomeFrontCard.swift
  ttakkeun/ttakkeun/Components/Home/ProfileImageCard.swift
  ttakkeun/ttakkeun/Components/Profile/ProfileSelect.swift
  ttakkeun/ttakkeun/DataModelGroup/PetProfile/HomeProfileResponseData.swift
  ttakkeun/ttakkeun/File/ImagePicker/HomeProfilePatchImagePicker.swift
  ttakkeun/ttakkeun/File/Protocol/HomePatchImage.swift
  ttakkeun/ttakkeun/ViewGroup/HomeTab/HomeDragView.swift
  ttakkeun/ttakkeun/ViewGroup/HomeTab/HomeProfileCard.swift
  ttakkeun/ttakkeun/ViewGroup/HomeTab/HomeView.swift
  ttakkeun/ttakkeun/ViewGroup/MyPage/MyPageDetailView.swift
  ttakkeun/ttakkeun/ViewGroup/MyPage/MyPageView.swift
  ttakkeun/ttakkeun/ViewModelGroup/HomeProfileCardViewModel.swift
  ttakkeun/ttakkeun/ViewModelGroup/MyPageViewModel.swift
Labels: :globe_with_meridians: API, :sparkles: Feature, :lipstick: UI

#123 ♻️ 홈 API 프로그레스 뷰 수정
  ttakkeun/ttakkeun/APITarget/ProductRecommendAPITarget.swift
  ttakkeun/ttakkeun/Components/Home/HomeAIRecommendProduct.swift
  ttakkeun/ttakkeun/Components/Home/HomeBackCard.swift
  ttakkeun/ttakkeun/Components/Home/HomeFrontCard.swift
  ttakkeun/ttakkeun/Components/Home/HomeUserRecommendProduct.swift
  ttakkeun/ttakkeun/DataModelGroup/Product/AIAndSearchProductData.swift
  ttakkeun/ttakkeun/DataModelGroup/Schedule/ScheduleInquiryData.swift
  ttakkeun/ttakkeun/ViewGroup/HomeTab/HomeDragView.swift
  ttakkeun/ttakkeun/ViewGroup/HomeTab/HomeProfileCard.swift
  ttakkeun/ttakkeun/ViewGroup/HomeTab/HomeView.swift
  ttakkeun/ttakkeun/ViewModelGroup/ProductViewModel.swift
  ttakkeun/ttakkeun/ViewModelGroup/ScheduleViewModel.swift
Labels: :bug: BugFix, :globe_with_meridians: API

#128 Feat/suggestion view
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/Recommend/ProductSheetView.swift
  ttakkeun/ttakkeun/Components/Recommend/RecommendProduct.swift
  ttakkeun/ttakkeun/DataModelGroup/RecommendProductData.swift
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/backBtn.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/backBtn.imageset/Vector 39.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/recommendDog.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/recommendDog.imageset/image 125.pdf
  ttakkeun/ttakkeun/SettingGroup/Color.swift
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/Suggestion/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/Suggestion/ProductBackground.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Icon.swift
  ttakkeun/ttakkeun/ViewGroup/Suggestion/SuggestionInitialView.swift
  ttakkeun/ttakkeun/ViewGroup/Suggestion/SuggestionSearchedView.swift
  ttakkeun/ttakkeun/ViewGroup/Suggestion/SuggestionView.swift
  ttakkeun/ttakkeun/ViewModelGroup/SuggestionViewModel.swift
Labels: :lipstick: UI

#131 최근에 완성된 tipsView
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/APITarget/QnaTipsAPITarget.swift
  ttakkeun/ttakkeun/Components/QnA/FloatingWrtieBtn.swift
  ttakkeun/ttakkeun/Components/QnA/TipContent.swift
  ttakkeun/ttakkeun/Components/QnA/TopTenQuestion.swift
  ttakkeun/ttakkeun/DataModelGroup/QnA/QnaHeartChangeData.swift
  ttakkeun/ttakkeun/DataModelGroup/QnA/QnaPostTipsData.swift
  ttakkeun/ttakkeun/DataModelGroup/QnA/QnaTipsData.swift
  ttakkeun/ttakkeun/EnumFile/DiagnosticResultAPITarget.swift
  ttakkeun/ttakkeun/EnumFile/TipsCategorySegment.swift
  ttakkeun/ttakkeun/ViewGroup/Qna/QnaFAQView.swift
  ttakkeun/ttakkeun/ViewGroup/Qna/QnaHeaderView.swift
  ttakkeun/ttakkeun/ViewGroup/Qna/QnaTipsView.swift
  ttakkeun/ttakkeun/ViewGroup/Qna/QnaView.swift
  ttakkeun/ttakkeun/ViewGroup/Qna/QnaWriteTipsView.swift
  ttakkeun/ttakkeun/ViewModelGroup/QnA/QnaTipsViewModel.swift
  ttakkeun/ttakkeun/ViewModelGroup/QnA/QnaWriteTipsViewModel.swift
Labels: :hammer: Refactor

#130 Refact/schedule view
  ttakkeun/ttakkeun/Components/Diary/TodoCard.swift
  ttakkeun/ttakkeun/Components/Home/ToDoCheckList.swift
  ttakkeun/ttakkeun/Components/Schedule/TodoControlSheet.swift
  ttakkeun/ttakkeun/ViewModelGroup/Diary/TodoCheckViewModel.swift
Labels: :hammer: Refactor, :lipstick: UI

#133 SuggestionAPI연결 완료
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/APITarget/SuggestionAPITarget.swift
  ttakkeun/ttakkeun/DataModelGroup/RecommendProductData.swift
  ttakkeun/ttakkeun/ViewGroup/Suggestion/SuggestionInitialView.swift
  ttakkeun/ttakkeun/ViewGroup/Suggestion/SuggestionView.swift
  ttakkeun/ttakkeun/ViewModelGroup/SuggestionViewModel.swift
Labels: :globe_with_meridians: API, :lipstick: UI

#134 Refact/schedule view
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/Diary/TodoCard.swift
Labels: :hammer: Refactor

#138 Refact/schedule view
  ttakkeun/ttakkeun/ViewModelGroup/Diary/TodoCheckViewModel.swift
Labels: :hammer: Refactor
