Repository ttakkeun/Front_iOS, pull requests merged in 2024-07, with the labels that each got.

#4 Feat/color
  ttakkeun/ttakkeun/SettingGroup/Color.swift
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/BorderColor.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/afterClaw.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/afterEar.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/afterEye.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/afterHair.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/afterTeeth.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/backColor.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/beforeClaw.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/beforeEar.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/beforeEye.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/beforeHair.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/beforeTeeth.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/card002.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/card003.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/card004.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/card005.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/fontColor.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/mainTextColor.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/primaryColor.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/profileFront.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/subTextColor.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/unClickedTab.colorset/Contents.json
  ttakkeun/ttakkeun/ViewGroup/ContentView.swift
Labels: :sparkles: Feature

#8 💄 달력 컴포넌트 만들기
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/CustomDiary.swift
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일정 화면/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일정 화면/downArrow.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/일정 화면/downArrow.imageset/Icon.pdf
  ttakkeun/ttakkeun/ViewModelGroup/CustomDiaryViewModel.swift
Labels: :lipstick: UI

#9 💄 프로필 개별 카드 생성
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/ProfileSelect.swift
  ttakkeun/ttakkeun/DataModelGroup/PetProfileData.swift
  ttakkeun/ttakkeun/EnumFile/ProfileType.swift
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/프로필 카드/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/프로필 카드/ProfileCat.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/프로필 카드/ProfileCat.imageset/ProfileCat.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/프로필 카드/ProfileDog.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/프로필 카드/ProfileDog.imageset/ProfileDog.pdf
  ttakkeun/ttakkeun/SettingGroup/Color.swift
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/subProfileColor.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/unclikedTab.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Icon.swift
  ttakkeun/ttakkeun/SettingGroup/ShadowReuse.swift
  ttakkeun/ttakkeun/ViewGroup/ProfileView.swift
  ttakkeun/ttakkeun/ViewModelGroup/ProfileCardViewModel.swift
Labels: :lipstick: UI

#10 ♻️ WeekBar 컴포넌트 추가
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/CustomDiary.swift
  ttakkeun/ttakkeun/Components/WeekBar.swift
  ttakkeun/ttakkeun/SettingGroup/Color.swift
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/weekBar.colorset/Contents.json
Labels: :hammer: Refactor

#11 💄 홈 프로필 카드
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/Home/HomeProfileCard.swift
  ttakkeun/ttakkeun/DataModelGroup/HomeProfileData.swift
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/홈/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/홈/editProfile.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/홈/editProfile.imageset/Vector.pdf
  ttakkeun/ttakkeun/SettingGroup/Color.swift
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/editColor.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Icon.swift
Labels: :lipstick: UI

#13 Feat/home componenets
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Componentes/Home/HomeProfileCard.swift
  ttakkeun/ttakkeun/Components/Home/HomeBackCard.swift
  ttakkeun/ttakkeun/Components/Home/HomeFrontCard.swift
  ttakkeun/ttakkeun/Components/Home/ProfileImageCard.swift
  ttakkeun/ttakkeun/Components/Profile/ProfileSelect.swift
  ttakkeun/ttakkeun/Components/Schedule/CustomDiary.swift
  ttakkeun/ttakkeun/Components/Schedule/WeekBar.swift
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/홈/changeCard.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/홈/changeCard.imageset/change.pdf
  ttakkeun/ttakkeun/SettingGroup/Color.swift
  ttakkeun/ttakkeun/SettingGroup/Icon.swift
  ttakkeun/ttakkeun/ViewModelGroup/HomeProfileCardViewModel.swift
Labels: :sparkles: Feature, :lipstick: UI

#15 ✨ 홈탭 드래그 뷰 구현
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/Home/HomeDragView.swift
  ttakkeun/ttakkeun/Components/Home/TestDragView.swift
  ttakkeun/ttakkeun/SettingGroup/Color.swift
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/sheetIndicator.colorset/Contents.json
Labels: :sparkles: Feature, :lipstick: UI

#18 커스텀 텍스트 필드 작성
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/ETC/CustomTextField.swift
  ttakkeun/ttakkeun/Components/ETC/topStatusBar.swift
  ttakkeun/ttakkeun/Components/Home/HomeDragView.swift
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/alarm.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/alarm.imageset/alarm.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/glass.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/glass.imageset/glass.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/setting.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/기타/setting.imageset/setting.pdf
  ttakkeun/ttakkeun/SettingGroup/Icon.swift
Labels: :sparkles: Feature, :lipstick: UI

#19 ✨ 이미지 앨범 피커뷰 생성
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/File/ImagePicker/ImageHandling.swift
  ttakkeun/ttakkeun/File/ImagePicker/RegistImagePicker.swift
Labels: :sparkles: Feature

#20 ✨ 프로필 이미지 선택 피커뷰 생성
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/File/ImagePicker/PetImagePicker.swift
  ttakkeun/ttakkeun/File/ImagePicker/ProfileImageRegistPicker.swift
Labels: :sparkles: Feature, :lipstick: UI

#23 🎨 파일 복사본 변경
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/Home/HomeAIRecommendProduct.swift
  ttakkeun/ttakkeun/Components/Home/HomeBackCard.swift
  ttakkeun/ttakkeun/Components/Home/HomeDragView.swift
  ttakkeun/ttakkeun/Components/Home/HomeFrontCard.swift
  ttakkeun/ttakkeun/Components/Home/HomeNotTodo.swift
  ttakkeun/ttakkeun/Components/Home/HomeNotTodoCircle.swift
  ttakkeun/ttakkeun/Components/Home/HomeUserRecommendProduct 2.swift
  ttakkeun/ttakkeun/Components/Home/ProfileImageCard.swift
  ttakkeun/ttakkeun/Components/Home/TestDragView.swift
Labels: :sparkles: Feature, :lipstick: UI

#24 💄 CustomAlert Component구현
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/ETC/CustomAlert.swift
  ttakkeun/ttakkeun/SettingGroup/Color.swift
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/noBtn.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/yesBtn.colorset/Contents.json
Labels: :lipstick: UI

#27 ✨ LoginAPI 타겟 연결
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/APITarget/AuthAPITarget.swift
  ttakkeun/ttakkeun/APITarget/UserLoginAPITarget.swift
  ttakkeun/ttakkeun/DataModelGroup/LoginData.swift
  ttakkeun/ttakkeun/DataModelGroup/LoginResponseData.swift
  ttakkeun/ttakkeun/File/KeyChain/KeyChainManager.swift
  ttakkeun/ttakkeun/File/KeyChain/UserInfo.swift
  ttakkeun/ttakkeun/File/TokenRefresh/TokenProvider.swift
  ttakkeun/ttakkeun/File/TokenRefresh/TokenResponse.swift
  ttakkeun/ttakkeun/ViewGroup/LoginView.swift
  ttakkeun/ttakkeun/ViewModelGroup/LoginViewModel.swift
Labels: :globe_with_meridians: API

#29 Feat/profile view
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/APITarget/AuthAPITarget.swift
  ttakkeun/ttakkeun/APITarget/PetProfileAPITarget.swift
  ttakkeun/ttakkeun/Components/Profile/ProfileSelect.swift
  ttakkeun/ttakkeun/DataModelGroup/PetProfileData.swift
  ttakkeun/ttakkeun/DataModelGroup/TodoCompleteData.swift
  ttakkeun/ttakkeun/EnumFile/ProfileType.swift
  ttakkeun/ttakkeun/File/PetState.swift
  ttakkeun/ttakkeun/File/TokenRefresh/TokenProvider.swift
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/프로필 카드/ProfileCat.imageset/ProfileCat.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/프로필 카드/ProfileDog.imageset/ProfileDog.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/프로필 카드/togetherPet.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/프로필 카드/togetherPet.imageset/togetherPet.pdf
  ttakkeun/ttakkeun/SettingGroup/Color.swift
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/Profile/Card003.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Icon.swift
  ttakkeun/ttakkeun/ViewGroup/ProfileView.swift
  ttakkeun/ttakkeun/ViewModelGroup/ProfileCardViewModel.swift
Labels: :globe_with_meridians: API, :lipstick: UI

#30 ✨ 프로필 관련 API 타겟 생성
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/APITarget/AuthAPITarget.swift
  ttakkeun/ttakkeun/APITarget/PetProfileAPITarget.swift
  ttakkeun/ttakkeun/DataModelGroup/PetProfile/CreatePetProfileRequestData.swift
  ttakkeun/ttakkeun/DataModelGroup/PetProfile/HomeProfileData.swift
  ttakkeun/ttakkeun/DataModelGroup/PetProfile/PetProfileData.swift
  ttakkeun/ttakkeun/DataModelGroup/PetProfile/PetProfileImageData.swift
  ttakkeun/ttakkeun/File/TokenRefresh/TokenProvider.swift
  ttakkeun/ttakkeun/File/TokenRefresh/TokenResponse.swift
  ttakkeun/ttakkeun/ViewGroup/ProfileView.swift
Labels: :page_facing_up: Docs, :globe_with_meridians: API, :sparkles: Feature

#32 ♻️ 프로필 뷰 nil값일 경우 수정
  ttakkeun/ttakkeun/APITarget/PetProfileAPITarget.swift
  ttakkeun/ttakkeun/Components/Profile/ProfileSelect.swift
  ttakkeun/ttakkeun/DataModelGroup/PetProfile/PetProfileData.swift
  ttakkeun/ttakkeun/File/TokenRefresh/TokenProvider.swift
  ttakkeun/ttakkeun/ViewGroup/ProfileView.swift
  ttakkeun/ttakkeun/ViewModelGroup/ProfileCardViewModel.swift
Labels: :hammer: Refactor, :lipstick: UI

#36 상세 product sheet View 구현
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/ETC/MainButton.swift
  ttakkeun/ttakkeun/Components/Recommend/ProductSheetView.swift
  ttakkeun/ttakkeun/DataModelGroup/RecommendProductData.swift
Labels: :hammer: Refactor, :lipstick: UI

#42 ✨ 홈 프로필 카드 뷰모델 추가 후 API 연결
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/Home/HomeBackCard.swift
  ttakkeun/ttakkeun/Components/Home/HomeFrontCard.swift
  ttakkeun/ttakkeun/Components/Home/ProfileImageCard.swift
  ttakkeun/ttakkeun/DataModelGroup/PetProfile/HomeProfileData.swift
  ttakkeun/ttakkeun/EnumFile/ProfileType.swift
  ttakkeun/ttakkeun/ViewGroup/HomeTab/HomeProfileCard.swift
  ttakkeun/ttakkeun/ViewGroup/ProfileView.swift
  ttakkeun/ttakkeun/ViewModelGroup/HomeProfileCardViewModel.swift
Labels: :globe_with_meridians: API, :hammer: Refactor, :lipstick: UI

#50 💄 프로필 네임 태크 컴포넌트 작성
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/Profile/MakeProfileTitle.swift
Labels: :lipstick: UI

#52 Feat/make profile
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/Profile/MakeProfileNameTag.swift
Labels: :hammer: Refactor

#54 Feat/home schedule
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/APITarget/ScheduleAPITarget.swift
  ttakkeun/ttakkeun/Components/ETC/TopStatusBar.swift
  ttakkeun/ttakkeun/Components/Home/HomeAINotRecommend.swift
  ttakkeun/ttakkeun/Components/Home/HomeNotTodo.swift
  ttakkeun/ttakkeun/Components/Home/HomeNotTodoCircle.swift
  ttakkeun/ttakkeun/Components/Home/HomeTodoCircle.swift
  ttakkeun/ttakkeun/Components/Home/ToDoCheckList.swift
  ttakkeun/ttakkeun/Components/Schedule/TodoCompleteEach.swift
  ttakkeun/ttakkeun/DataModelGroup/Schedule/ScheduleInquiryData.swift
  ttakkeun/ttakkeun/DataModelGroup/Schedule/TodoCompleteData.swift
  ttakkeun/ttakkeun/EnumFile/PartItem.swift
  ttakkeun/ttakkeun/File/TokenRefresh/AuthAPITarget.swift
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/홈/checkBox.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/홈/checkBox.imageset/checkBox.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/홈/checkV.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/홈/checkV.imageset/checkV.pdf
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/홈/unCheckBox.imageset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Assets.xcassets/홈/unCheckBox.imageset/unCheckBox.pdf
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/HomeTodo/afterEar.colorset/Contents.json
  ttakkeun/ttakkeun/SettingGroup/Icon.swift
  ttakkeun/ttakkeun/SettingGroup/ttakkeunApp.swift
  ttakkeun/ttakkeun/ViewGroup/HomeTab/CompactTodo.swift
  ttakkeun/ttakkeun/ViewGroup/HomeTab/ExpandTodo.swift
  ttakkeun/ttakkeun/ViewGroup/ProfileView.swift
  ttakkeun/ttakkeun/ViewModelGroup/LoginViewModel.swift
  ttakkeun/ttakkeun/ViewModelGroup/ProfileCardViewModel.swift
  ttakkeun/ttakkeun/ViewModelGroup/ScheduleViewModel.swift
Labels: :globe_with_meridians: API, :sparkles: Feature, :lipstick: UI

#55 💄 Color 정의 및 not AI 추천 구현
  ttakkeun/ttakkeun/Components/Home/HomeAINotRecommend.swift
  ttakkeun/ttakkeun/SettingGroup/Color.swift
  ttakkeun/ttakkeun/SettingGroup/Color.xcassets/Profile/RedStar.colorset/Contents.json
Labels: :hammer: Refactor, :lipstick: UI

#58 Feat/home ai product
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/APITarget/ProductRecommendAPITarget.swift
  ttakkeun/ttakkeun/Components/Home/HomeAINotRecommend.swift
  ttakkeun/ttakkeun/Components/Home/HomeAIRecommendProduct.swift
  ttakkeun/ttakkeun/Components/Home/HomeUserRecommendProduct.swift
  ttakkeun/ttakkeun/DataModelGroup/AIRecommendProductData.swift
  ttakkeun/ttakkeun/DataModelGroup/Product/AIRecommendProductData.swift
  ttakkeun/ttakkeun/DataModelGroup/UserRecommendProductData.swift
  ttakkeun/ttakkeun/ViewModelGroup/ProductViewModel.swift
Labels: :globe_with_meridians: API, :sparkles: Feature, :lipstick: UI

#61 ✨ DragView 수정
  ttakkeun/ttakkeun.xcodeproj/project.pbxproj
  ttakkeun/ttakkeun/Components/Home/HomeBackCard.swift
  ttakkeun/ttakkeun/Components/Home/HomeFrontCard.swift
  ttakkeun/ttakkeun/DataModelGroup/Product/AIAndSearchProductData.swift
  ttakkeun/ttakkeun/File/PetState.swift
  ttakkeun/ttakkeun/SettingGroup/ShadowReuse.swift
  ttakkeun/ttakkeun/ViewGroup/HomeTab/HomeDragView.swift
  ttakkeun/ttakkeun/ViewGroup/HomeTab/HomeView.swift
  ttakkeun/ttakkeun/ViewModelGroup/ProductViewModel.swift
Labels: :page_facing_up: Docs, :lipstick: UI
